import { jsPDF } from "jspdf";
import { SHOP_INFO, shopLogo } from "@/lib/shop-info";
import { fmtCard, fmtCell, isNumericFmt } from "@/lib/reports/format";
import type { ReportResult, ReportTable } from "@/lib/reports/types";

const fileStem = (r: ReportResult) => `${r.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}-${new Date().toISOString().slice(0, 10)}`;

function download(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

const csvCell = (v: string | number | null | undefined) => {
  const s = v === null || v === undefined ? "" : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

/** Plain numbers for money/percent columns so Excel can add them up; dates are readable. */
function csvValue(v: string | number | null | undefined, fmt?: string) {
  if (v === null || v === undefined) return "";
  if (fmt === "date" || fmt === "datetime") return fmtCell(v, fmt);
  return v;
}

export function exportCsv(r: ReportResult, meta: { by: string }) {
  const out: string[] = [SHOP_INFO.name, r.title, `Period,${csvCell(r.periodLabel)}`, `Generated,${csvCell(new Date().toLocaleString("en-US"))}`, `Generated by,${csvCell(meta.by)}`, ""];
  if (r.cards.length) {
    out.push("Summary");
    for (const c of r.cards) out.push(`${csvCell(c.label)},${csvCell(c.value)}`);
    out.push("");
  }
  if (r.cashRecon) {
    out.push("Cash reconciliation");
    for (const l of r.cashRecon.lines) out.push(`${csvCell(l.label)},${csvCell(l.value)}`);
    out.push("");
  }
  for (const t of r.tables) {
    if (t.title) out.push(csvCell(t.title));
    out.push(t.cols.map((c) => csvCell(c.label)).join(","));
    for (const row of t.rows) out.push(t.cols.map((c) => csvCell(csvValue(row[c.key], c.fmt))).join(","));
    if (t.totals) out.push(t.cols.map((c) => csvCell(csvValue(t.totals![c.key], c.fmt))).join(","));
    out.push("");
  }
  // The BOM makes Excel read the file as UTF-8.
  download(new Blob(["﻿" + out.join("\r\n")], { type: "text/csv;charset=utf-8" }), `${fileStem(r)}.csv`);
}

type RGB = [number, number, number];
const ACCENT: RGB = [234, 88, 12];
const TEXT: RGB = [24, 24, 27];
const MUTED: RGB = [113, 113, 122];
const LINE: RGB = [228, 228, 231];
const HEAD: RGB = [244, 244, 245];

export function exportPdf(r: ReportResult, meta: { by: string }) {
  const wide = r.tables.some((t) => t.cols.length > 6);
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: wide ? "landscape" : "portrait" });
  const W = wide ? 297 : 210;
  const H = wide ? 210 : 297;
  const M = 12;
  const R = W - M;
  let y = 0;

  const header = () => {
    const logo = shopLogo();
    let x = M;
    if (logo) {
      doc.addImage(logo.data, logo.format, M, 8, 16, 16);
      x = M + 20;
    }
    doc.setFont("helvetica", "bold").setFontSize(14).setTextColor(...TEXT);
    doc.text(SHOP_INFO.name, x, 14);
    doc.setFont("helvetica", "normal").setFontSize(8).setTextColor(...MUTED);
    doc.text(`Generated ${new Date().toLocaleString("en-US")} by ${meta.by}`, x, 19);
    doc.setFont("helvetica", "bold").setFontSize(15).setTextColor(...ACCENT);
    doc.text(r.title, R, 14, { align: "right" });
    doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(...MUTED);
    doc.text(r.periodLabel, R, 19, { align: "right" });
    doc.setDrawColor(...LINE).setLineWidth(0.4).line(M, 26, R, 26);
    y = 32;
  };
  const room = (h: number) => {
    if (y + h > H - 14) {
      doc.addPage();
      header();
    }
  };

  header();

  if (r.cards.length) {
    const colW = (R - M) / 2;
    r.cards.forEach((c, i) => {
      if (i % 2 === 0) room(8);
      const x = M + (i % 2) * colW;
      doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(...MUTED);
      doc.text(c.label, x, y);
      doc.setFont("helvetica", "bold").setFontSize(10).setTextColor(...TEXT);
      doc.text(fmtCard(c.value, c.fmt), x + colW - 6, y, { align: "right" });
      if (i % 2 === 1 || i === r.cards.length - 1) y += 7;
    });
    y += 3;
  }

  if (r.cashRecon) {
    room(8 + r.cashRecon.lines.length * 6);
    doc.setFont("helvetica", "bold").setFontSize(10).setTextColor(...TEXT);
    doc.text("Cash reconciliation", M, y);
    y += 6;
    for (const l of r.cashRecon.lines) {
      doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(...MUTED);
      doc.text(l.label, M, y);
      doc.setTextColor(...TEXT);
      doc.text(fmtCard(l.value, "money"), R, y, { align: "right" });
      y += 6;
    }
    y += 2;
  }

  const drawTable = (t: ReportTable) => {
    const rows = [...t.rows, ...(t.totals ? [t.totals] : [])];
    if (t.title) {
      room(16);
      doc.setFont("helvetica", "bold").setFontSize(10).setTextColor(...TEXT);
      doc.text(t.title, M, y);
      y += 5;
    }
    // Number columns get a fixed share; text columns split the rest by how long their text is.
    const avail = R - M;
    const weights = t.cols.map((c) => (isNumericFmt(c.fmt) ? 1 : c.fmt === "date" || c.fmt === "datetime" ? 1 : Math.min(3, 1 + Math.max(c.label.length, ...rows.slice(0, 40).map((row) => String(row[c.key] ?? "").length)) / 14)));
    const sum = weights.reduce((a, b) => a + b, 0);
    const widths = weights.map((w) => (w / sum) * avail);
    const drawHead = () => {
      room(10);
      doc.setFillColor(...HEAD).rect(M, y - 4, avail, 7, "F");
      doc.setFont("helvetica", "bold").setFontSize(8).setTextColor(...TEXT);
      let x = M;
      t.cols.forEach((c, i) => {
        const label = doc.splitTextToSize(c.label, widths[i] - 2)[0];
        if (isNumericFmt(c.fmt)) doc.text(label, x + widths[i] - 1, y, { align: "right" });
        else doc.text(label, x + 1, y);
        x += widths[i];
      });
      y += 6;
    };
    drawHead();
    rows.forEach((row, ri) => {
      const isTotal = t.totals && ri === rows.length - 1;
      const cells = t.cols.map((c, i) => doc.splitTextToSize(fmtCell(row[c.key], c.fmt), widths[i] - 2) as string[]);
      const lines = Math.min(3, Math.max(...cells.map((c) => c.length)));
      const h = lines * 3.6 + 2;
      if (y + h > H - 14) {
        doc.addPage();
        header();
        drawHead();
      }
      doc.setFont("helvetica", isTotal ? "bold" : "normal").setFontSize(8).setTextColor(...TEXT);
      let x = M;
      t.cols.forEach((c, i) => {
        const parts = cells[i].slice(0, lines);
        parts.forEach((p, li) => {
          if (isNumericFmt(c.fmt)) doc.text(p, x + widths[i] - 1, y + li * 3.6, { align: "right" });
          else doc.text(p, x + 1, y + li * 3.6);
        });
        x += widths[i];
      });
      doc.setDrawColor(...LINE).setLineWidth(0.2).line(M, y + h - 3.4, R, y + h - 3.4);
      y += h;
    });
    y += 5;
  };
  for (const t of r.tables) drawTable(t);

  if (r.notes.length) {
    room(8 + r.notes.length * 4);
    doc.setFont("helvetica", "italic").setFontSize(8).setTextColor(...MUTED);
    for (const n of r.notes) {
      const parts = doc.splitTextToSize(n, R - M) as string[];
      for (const p of parts) {
        room(5);
        doc.text(p, M, y);
        y += 4;
      }
    }
  }

  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal").setFontSize(8).setTextColor(...MUTED);
    doc.text(`Page ${p} of ${pages}`, R, H - 6, { align: "right" });
  }
  doc.save(`${fileStem(r)}.pdf`);
}
